#!/usr/bin/env python3
"""Tests for skf-disqualify-candidates.py.

Covers:
  - find_generated_segment: node_modules/, vendor/, __pycache__/, .next/,
    .gradle/ at any depth; dist/, build/, target/ only as the first folder
    or beside a manifest (a Java package folder named build/ is source)
  - below_boundary: the segment is looked for below the boundary path
  - is_lockfile / is_non_source: lockfiles, documentation, data, media,
    binaries, manifests and build and tool configuration are never source
    files; unknown extensions are
  - has_auto_generated_marker: @generated / // GENERATED CODE /
    # AUTOGENERATED / <!-- generated --> within first 10 lines
  - count_nonblank_lines: empty file, whitespace-only lines, trailing
    newline, mix of content + blanks
  - evaluate_boundary: a boundary drops as generated only when every source
    file is generated; the reproduced cases (a crate with Cargo.lock, a
    package with src/build/, a Go module with vendor/, a Maven module with
    a com/acme/build/ package) stay; counts leave out lockfiles, non-source
    and generated files; passes_with_generated; rule order; kept records
  - manifest: the own manifest's path, ecosystem, name and private flag
  - signals: each presence flag and its limits
  - filter_boundaries: stats by_reason and mixed, kept/dropped partitions,
    empty input
  - validate_boundaries: missing name/path, wrong types; `files` optional
  - listing: a boundary without `files` gets what git lists under its
    path (ignored build output and dependencies out, each path once), or a
    walk that skips node_modules/ and __pycache__/ outside a work tree or
    in a folder the outer work tree ignores; hidden entries out either way;
    `./packages/auth` and `packages/auth/` list `packages/auth`, and a path
    that leaves the source root exits 1; --tree-dir writes each boundary's
    list (UTF-8, whatever the names) and its record names it in
    `tree_file`, which skf-detect-language.py reads
  - CLI: file input, stdin (-) piping, exit codes for malformed input
  - the manifest names and readers come from skf-scan-manifests.py (hence
    the Python 3.11 floor), and identify-units.md, map-and-detect.md,
    generate-briefs.md and unit-detection-heuristics.md describe the
    helpers as they work
"""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).parent.parent
SCRIPT_PATH = (
    REPO_ROOT / "src" / "shared" / "scripts" / "skf-disqualify-candidates.py"
)
SCAN_MANIFESTS_PATH = (
    REPO_ROOT / "src" / "shared" / "scripts" / "skf-scan-manifests.py"
)
ANALYZE_REFS = REPO_ROOT / "src" / "skf-analyze-source" / "references"
IDENTIFY_UNITS = ANALYZE_REFS / "identify-units.md"
HEURISTICS = ANALYZE_REFS / "unit-detection-heuristics.md"
MAP_AND_DETECT = ANALYZE_REFS / "map-and-detect.md"
UNIT_EXPORTS = ANALYZE_REFS / "map-unit-exports.md"
GENERATE_BRIEFS = ANALYZE_REFS / "generate-briefs.md"


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


mod = _load("skf_disqualify_candidates", SCRIPT_PATH)


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------


def _write(path: Path, content: str = "") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content.encode("utf-8"))
    return path


def _boundary(name: str, path: str, files: list[str]) -> dict:
    return {"name": name, "path": path, "files": files}


def _make_files(
    source_root: Path, boundary_path: str, file_specs: dict[str, str]
) -> list[str]:
    """Materialize <source_root>/<boundary_path>/<file_rel> for each entry
    in file_specs and return the list of `files[]` paths in source-root-
    relative form (matching how scan-project would record them).
    """
    files: list[str] = []
    for rel, content in file_specs.items():
        full = source_root / boundary_path / rel
        _write(full, content)
        # source-root-relative form, forward-slash for cross-platform JSON
        files.append((Path(boundary_path) / rel).as_posix())
    return files


def _evaluate(
    tmp_path: Path, name: str, path: str, files: list[str], **kwargs
) -> dict:
    return mod.evaluate_boundary(
        _boundary(name, path, files), source_root=tmp_path, **kwargs
    )


BODY_40 = "x = 1\n" * 40  # 40 non-blank lines


# --------------------------------------------------------------------------
# find_generated_segment / below_boundary
# --------------------------------------------------------------------------


class TestFindGeneratedSegment:
    def test_node_modules_at_root(self) -> None:
        assert mod.find_generated_segment("node_modules/react/index.js") == "node_modules/"

    def test_node_modules_nested(self) -> None:
        assert (
            mod.find_generated_segment("packages/ui/node_modules/foo/index.js")
            == "node_modules/"
        )

    def test_vendor(self) -> None:
        assert mod.find_generated_segment("vendor/lib.go") == "vendor/"

    def test_dist(self) -> None:
        assert mod.find_generated_segment("dist/bundle.js") == "dist/"

    def test_build(self) -> None:
        assert mod.find_generated_segment("build/output.so") == "build/"

    def test_pycache(self) -> None:
        assert (
            mod.find_generated_segment("src/__pycache__/foo.cpython-310.pyc")
            == "__pycache__/"
        )

    def test_next(self) -> None:
        assert mod.find_generated_segment(".next/server.js") == ".next/"

    def test_target_rust(self) -> None:
        assert mod.find_generated_segment("target/debug/foo") == "target/"

    def test_gradle(self) -> None:
        assert mod.find_generated_segment(".gradle/caches/x.jar") == ".gradle/"

    def test_clean_path_returns_none(self) -> None:
        assert mod.find_generated_segment("src/main.py") is None

    def test_backslash_normalized(self) -> None:
        # Windows-style separators get folded to forward-slash before match
        assert (
            mod.find_generated_segment(r"packages\ui\node_modules\foo.js")
            == "node_modules/"
        )

    def test_substring_alone_does_not_match(self) -> None:
        # `dist` with no trailing slash is not a directory segment, so a
        # filename like `redistribute.py` does not match
        assert mod.find_generated_segment("src/redistribute.py") is None

    @pytest.mark.parametrize("path", [
        "src/build/index.ts",
        "src/main/java/com/acme/build/Graph.java",
        "lib/dist/format.py",
        "pkg/target/select.go",
    ])
    def test_output_folder_further_down_is_source(self, path: str) -> None:
        assert mod.find_generated_segment(path) is None

    def test_output_folder_beside_a_manifest(self) -> None:
        dirs = {"packages/web"}
        path = "packages/web/dist/index.js"
        assert mod.find_generated_segment(path, dirs) == "dist/"
        assert mod.find_generated_segment(path) is None
        assert mod.find_generated_segment("./build/x.js") == "build/"

    def test_vendored_folders_at_any_depth(self) -> None:
        assert mod.find_generated_segment("a/b/vendor/x.go") == "vendor/"
        assert mod.find_generated_segment("a/.gradle/c/x.kt") == ".gradle/"

    def test_leftmost_folder_wins(self) -> None:
        assert mod.find_generated_segment("build/node_modules/x.js") == "build/"
        assert mod.find_generated_segment("src/build/vendor/x.go") == "vendor/"


class TestBelowBoundary:
    def test_strips_the_boundary_path(self) -> None:
        rel = mod.below_boundary("packages/build/src/index.ts", "packages/build")
        assert rel == "src/index.ts"

    def test_root_boundary_keeps_the_path(self) -> None:
        assert mod.below_boundary("dist/x.js", "") == "dist/x.js"
        assert mod.below_boundary("dist/x.js", ".") == "dist/x.js"

    def test_boundary_relative_entry_kept_whole(self) -> None:
        assert mod.below_boundary("src/a.ts", "pkg/a") == "src/a.ts"

    def test_prefix_must_end_at_a_folder(self) -> None:
        assert mod.below_boundary("pkg/abc/x.ts", "pkg/a") == "pkg/abc/x.ts"


# --------------------------------------------------------------------------
# File kinds
# --------------------------------------------------------------------------


@pytest.mark.parametrize("name", [
    "Cargo.lock", "package-lock.json", "npm-shrinkwrap.json", "yarn.lock",
    "pnpm-lock.yaml", "poetry.lock", "Pipfile.lock", "uv.lock", "composer.lock",
    "Gemfile.lock", "go.sum", "bun.lockb", "gradle.lockfile", "Package.resolved",
    "crates/core/Cargo.lock",
])
def test_lockfiles(name: str) -> None:
    assert mod.is_lockfile(name)
    assert mod.is_non_source(name)


@pytest.mark.parametrize("name", ["src/lock.rs", "clock.py", "locker.ts", "lockfile.go"])
def test_names_near_lockfiles_are_source(name: str) -> None:
    assert not mod.is_lockfile(name)
    assert not mod.is_non_source(name)


@pytest.mark.parametrize("name", [
    "README.md", "docs/guide.rst", "notes.txt", "package.json", "Cargo.toml",
    "pyproject.toml", "setup.cfg", "config.yaml", "pom.xml", "go.mod", "LICENSE",
    "LICENSE-MIT", "CHANGELOG", "Makefile", "Dockerfile", "Dockerfile.dev",
    "web.dockerfile", ".gitignore", ".eslintrc.js", "logo.png", "icon.svg",
    "font.woff2", "lib.so", "app.jar", "bundle.js.map", "__snapshots__/a.snap",
])
def test_non_source_files(name: str) -> None:
    assert mod.is_non_source(name)


@pytest.mark.parametrize("name", [
    # manifests that are code
    "setup.py", "build.gradle", "build.gradle.kts", "Package.swift",
    # build tools
    "settings.gradle", "settings.gradle.kts", "gradlew", "gradlew.bat", "mvnw",
    "mvnw.cmd", "BUILD", "BUILD.bazel", "WORKSPACE", "MODULE.bazel",
    # tool configuration
    "vite.config.ts", "jest.config.js", "babel.config.cjs", "web/webpack.config.mjs",
])
def test_build_and_tool_configuration_is_not_source(name: str) -> None:
    """A JS package of index.ts and two config files is one source file."""
    assert mod.is_non_source(name)


@pytest.mark.parametrize("name", [
    "main.rs", "src/index.ts", "App.tsx", "mod.py", "server.go", "Main.java",
    "schema.proto", "query.graphql", "run.sh", "view.vue", "lib.zig", "app.ex",
    "noext", "config.ts", "src/build.rs", "setup_utils.py",
])
def test_source_files(name: str) -> None:
    assert not mod.is_non_source(name)


# --------------------------------------------------------------------------
# has_auto_generated_marker
# --------------------------------------------------------------------------


class TestAutoGeneratedMarker:
    def test_at_generated_line_1(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "# @generated\nprint('hi')\n")
        assert mod.has_auto_generated_marker(f) == "@generated"

    def test_generated_code_comment(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.ts", "// GENERATED CODE: DO NOT EDIT\nexport {}\n")
        assert mod.has_auto_generated_marker(f) == "// generated code"

    def test_autogenerated_python_comment(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "# AUTOGENERATED FILE\nx = 1\n")
        assert mod.has_auto_generated_marker(f) == "# autogenerated"

    def test_html_comment(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.html", "<!-- generated -->\n<html></html>\n")
        assert mod.has_auto_generated_marker(f) == "<!-- generated -->"

    def test_case_insensitive(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "# @Generated by tool\nx = 1\n")
        assert mod.has_auto_generated_marker(f) == "@generated"

    def test_within_first_10_lines(self, tmp_path: Path) -> None:
        # marker at line 10: still within the scan window
        body = "\n".join([f"# line {i}" for i in range(1, 10)] + ["@generated"]) + "\n"
        f = _write(tmp_path / "f.py", body)
        assert mod.has_auto_generated_marker(f) == "@generated"

    def test_beyond_first_10_lines_misses(self, tmp_path: Path) -> None:
        # marker at line 12: outside the scan window
        body = "\n".join(
            [f"# line {i}" for i in range(1, 12)] + ["// GENERATED CODE"]
        ) + "\n"
        f = _write(tmp_path / "f.py", body)
        assert mod.has_auto_generated_marker(f) is None

    def test_no_marker(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "def foo():\n    return 1\n")
        assert mod.has_auto_generated_marker(f) is None

    def test_unreadable_file_returns_none(self, tmp_path: Path) -> None:
        # nonexistent file: silently None (the header scan is opportunistic)
        assert mod.has_auto_generated_marker(tmp_path / "missing.py") is None


# --------------------------------------------------------------------------
# count_nonblank_lines
# --------------------------------------------------------------------------


class TestCountNonblankLines:
    def test_empty_file(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "")
        assert mod.count_nonblank_lines(f) == 0

    def test_only_whitespace(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "   \n\t\n  \n")
        assert mod.count_nonblank_lines(f) == 0

    def test_mixed_content_and_blanks(self, tmp_path: Path) -> None:
        f = _write(
            tmp_path / "f.py",
            "import os\n"   # 1
            "\n"            # blank
            "def foo():\n"  # 2
            "   \n"         # whitespace-only: blank
            "    return 1\n"  # 3
        )
        assert mod.count_nonblank_lines(f) == 3

    def test_trailing_newline(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "x = 1\ny = 2\n")
        assert mod.count_nonblank_lines(f) == 2

    def test_no_trailing_newline(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "x = 1\ny = 2")  # no trailing \n
        assert mod.count_nonblank_lines(f) == 2

    def test_missing_file_returns_zero(self, tmp_path: Path) -> None:
        assert mod.count_nonblank_lines(tmp_path / "missing.py") == 0


# --------------------------------------------------------------------------
# evaluate_boundary: the reproduced cases (#582)
# --------------------------------------------------------------------------


class TestReproducedCases:
    """One generated file used to drop the whole boundary."""

    def test_crate_with_committed_cargo_lock_is_kept(self, tmp_path: Path) -> None:
        files = _make_files(tmp_path, "crates/core", {
            "Cargo.toml": '[package]\nname = "core"\n',
            "Cargo.lock": "# This file is automatically @generated by Cargo.\n"
                          "# It is not intended for manual editing.\nversion = 3\n",
            "src/lib.rs": "pub fn a() {}\n" * 40,
            "src/parse.rs": "pub fn b() {}\n" * 40,
            "src/emit.rs": "pub fn c() {}\n" * 40,
        })
        result = _evaluate(tmp_path, "core", "crates/core", files)
        assert result["kind"] == "kept"
        record = result["record"]
        assert record["generated_files"] == []
        assert record["generated_ratio"] == 0.0
        assert record["files_count"] == 3
        assert record["loc_total"] == 120
        assert record["non_source_count"] == 2  # Cargo.toml and Cargo.lock

    def test_package_with_real_src_build_is_kept(self, tmp_path: Path) -> None:
        files = _make_files(tmp_path, "packages/web", {
            "package.json": '{"name": "@acme/web"}\n',
            "src/index.ts": "export const a = 1;\n" * 40,
            "src/client.ts": "export const b = 1;\n" * 40,
            "src/server.ts": "export const c = 1;\n" * 40,
            "src/build/index.ts": "export const d = 1;\n" * 40,
            "dist/index.js": "exports.a = 1;\n" * 40,
        })
        result = _evaluate(tmp_path, "web", "packages/web", files)
        assert result["kind"] == "kept"
        record = result["record"]
        # src/build/ is the package's own code; dist/ below its root is output
        assert record["generated_files"] == [{
            "path": "packages/web/dist/index.js",
            "reason": "generated-code",
            "match": "dist/",
        }]
        assert record["generated_ratio"] == 0.2
        assert record["files_count"] == 4

    def test_maven_module_with_a_build_package_is_kept(self, tmp_path: Path) -> None:
        """A Java package folder named build/ used to drop the whole module."""
        java = "src/main/java/com/acme/build"
        files = _make_files(tmp_path, "graph", {
            "pom.xml": "<project><groupId>com.acme</groupId>"
                       "<artifactId>graph</artifactId></project>\n",
            f"{java}/Graph.java": "package com.acme.build;\n" * 40,
            f"{java}/Node.java": "package com.acme.build;\n" * 40,
            f"{java}/Edge.java": "package com.acme.build;\n" * 40,
            "target/classes/Graph.class": "",
        })
        result = _evaluate(tmp_path, "graph", "graph", files)
        assert result["kind"] == "kept"
        record = result["record"]
        assert (record["generated_files"], record["files_count"]) == ([], 3)
        assert record["manifest"] == {
            "path": "graph/pom.xml", "ecosystem": "maven",
            "name": "com.acme:graph", "private": False,
        }

    def test_member_package_dist_is_output(self, tmp_path: Path) -> None:
        files = _make_files(tmp_path, "", {
            "packages/ui/package.json": '{"name": "@acme/ui"}\n',
            "packages/ui/src/a.ts": BODY_40,
            "packages/ui/dist/a.js": BODY_40,
            "lib/dist/b.ts": BODY_40,
        })
        record = _evaluate(tmp_path, "root", "", files)["record"]
        assert [g["path"] for g in record["generated_files"]] == ["packages/ui/dist/a.js"]

    def test_go_module_with_vendor_is_kept(self, tmp_path: Path) -> None:
        files = _make_files(tmp_path, "svc", {
            "go.mod": "module example.com/svc\n",
            "go.sum": "github.com/pkg/errors v0.9.1 h1:abc\n",
            "main.go": "package main\n" * 40,
            "server.go": "package main\n" * 40,
            "handler.go": "package main\n" * 40,
            "vendor/github.com/pkg/errors/errors.go": "package errors\n" * 40,
            "vendor/github.com/pkg/errors/stack.go": "package errors\n" * 40,
            "vendor/modules.txt": "# github.com/pkg/errors v0.9.1\n",
        })
        result = _evaluate(tmp_path, "svc", "svc", files)
        assert result["kind"] == "kept"
        record = result["record"]
        assert [g["path"] for g in record["generated_files"]] == [
            "svc/vendor/github.com/pkg/errors/errors.go",
            "svc/vendor/github.com/pkg/errors/stack.go",
        ]
        assert {g["match"] for g in record["generated_files"]} == {"vendor/"}
        assert record["generated_ratio"] == 0.4
        assert record["files_count"] == 3
        assert record["non_source_count"] == 3  # go.mod, go.sum, vendor/modules.txt

    def test_one_generated_header_among_many_is_kept(self, tmp_path: Path) -> None:
        # four files, one opens with @generated: the old rule dropped them all
        files = _make_files(tmp_path, "pkg/protobuf", {
            "schema.py": "# @generated by codegen\n" + "y = 2\n" * 50,
            "model_a.py": "x = 1\n" * 50,
            "model_b.py": "x = 1\n" * 50,
            "model_c.py": "x = 1\n" * 50,
        })
        result = _evaluate(tmp_path, "protobuf", "pkg/protobuf", files)
        assert result["kind"] == "kept"
        assert result["record"]["generated_files"] == [{
            "path": "pkg/protobuf/schema.py",
            "reason": "auto-generated-tag",
            "match": "@generated",
        }]
        assert result["record"]["generated_ratio"] == 0.25

    def test_package_living_in_a_build_folder_is_not_generated(
        self, tmp_path: Path
    ) -> None:
        files = _make_files(tmp_path, "packages/build", {
            "package.json": '{"name": "@acme/build"}\n',
            "src/index.ts": BODY_40,
            "src/bundle.ts": BODY_40,
            "src/watch.ts": BODY_40,
        })
        result = _evaluate(tmp_path, "build", "packages/build", files)
        assert result["kind"] == "kept"
        assert result["record"]["generated_files"] == []


# --------------------------------------------------------------------------
# evaluate_boundary: rules and counts
# --------------------------------------------------------------------------


class TestEvaluateBoundary:
    def test_kept_boundary(self, tmp_path: Path) -> None:
        # 5 files * 30 non-blank lines = 150 LoC: passes both thresholds
        body = "x = 1\n" * 30
        files = _make_files(
            tmp_path,
            "pkg/auth",
            {f"file{i}.py": body for i in range(5)},
        )
        result = _evaluate(tmp_path, "auth", "pkg/auth", files)
        assert result["kind"] == "kept"
        assert result["record"]["name"] == "auth"
        assert result["record"]["path"] == "pkg/auth"
        assert result["record"]["files_count"] == 5
        assert result["record"]["loc_total"] == 150
        assert result["record"]["generated_ratio"] == 0.0
        assert result["record"]["passes_with_generated"] is True
        assert result["record"]["manifest"] is None

    def test_passes_with_generated(self, tmp_path: Path) -> None:
        """A size drop the flagged files caused says whether they would lift it."""
        files = _make_files(tmp_path, "tool", {
            "main.go": BODY_40,
            "build/gen.go": BODY_40,
            "build/types.go": BODY_40,
        })
        record = _evaluate(tmp_path, "tool", "tool", files)["record"]
        assert (record["reason"], record["files_count"]) == ("too-few-files", 1)
        assert record["passes_with_generated"] is True
        small = _make_files(tmp_path, "tiny", {
            "main.go": "package main\n",
            "build/gen.go": "package build\n",
            "build/more.go": "package build\n",
        })
        record = _evaluate(tmp_path, "tiny", "tiny", small)["record"]
        assert (record["reason"], record["passes_with_generated"]) == (
            "too-few-files", False)  # three files, three lines

    def test_dropped_too_few_files(self, tmp_path: Path) -> None:
        body = "x = 1\n" * 60  # plenty of LoC
        files = _make_files(
            tmp_path,
            "pkg/tiny",
            {f"f{i}.py": body for i in range(2)},
        )
        result = _evaluate(tmp_path, "tiny", "pkg/tiny", files)
        assert result["kind"] == "dropped"
        record = result["record"]
        assert record["reason"] == "too-few-files"
        assert record["path"] == "pkg/tiny"
        assert record["files_count"] == 2
        assert record["context"] == {"threshold": 3}

    def test_dropped_too_low_loc(self, tmp_path: Path) -> None:
        # 5 files * 12 lines = 60 LoC: below the 100 threshold
        body = "x = 1\n" * 12
        files = _make_files(
            tmp_path,
            "pkg/skinny",
            {f"f{i}.py": body for i in range(5)},
        )
        result = _evaluate(tmp_path, "skinny", "pkg/skinny", files)
        assert result["kind"] == "dropped"
        record = result["record"]
        assert record["reason"] == "too-low-loc"
        assert record["files_count"] == 5
        assert record["loc_total"] == 60
        assert record["context"] == {"threshold": 100}

    def test_all_vendored_is_generated_code(self, tmp_path: Path) -> None:
        # every source file under node_modules/: the path check is string-only
        files = [
            "vendor-app/node_modules/react/index.js",
            "vendor-app/node_modules/react/lib/foo.js",
            "vendor-app/node_modules/react/package.json",
        ]
        result = _evaluate(tmp_path, "vendor-app", "vendor-app", files)
        assert result["kind"] == "dropped"
        record = result["record"]
        assert record["reason"] == "generated-code"
        assert record["context"] == {
            "first_match": "vendor-app/node_modules/react/index.js",
            "matched_segment": "node_modules/",
        }
        assert record["generated_ratio"] == 1.0
        assert record["files_count"] == 0

    def test_all_headers_is_auto_generated_tag(self, tmp_path: Path) -> None:
        body_gen = "// @generated\n" + ("y = 2;\n" * 40)
        files = _make_files(
            tmp_path, "pkg/y", {f"f{i}.ts": body_gen for i in range(5)},
        )
        result = _evaluate(tmp_path, "y", "pkg/y", files)
        assert result["kind"] == "dropped"
        record = result["record"]
        assert record["reason"] == "auto-generated-tag"
        assert record["context"] == {
            "first_match": "pkg/y/f0.ts",
            "matched_sentinel": "@generated",
        }
        assert record["passes_with_generated"] is True  # 5 files, 205 lines

    def test_all_generated_by_both_kinds_reports_the_segment(
        self, tmp_path: Path
    ) -> None:
        files = _make_files(tmp_path, "pkg/z", {
            "api_pb.ts": "// @generated by protoc\nexport {};\n",
            "dist/index.js": "module.exports = {};\n",
        })
        result = _evaluate(tmp_path, "z", "pkg/z", files)
        assert result["record"]["reason"] == "generated-code"
        assert result["record"]["context"]["first_match"] == "pkg/z/dist/index.js"

    def test_mixed_vendored_and_small_drops_by_size(self, tmp_path: Path) -> None:
        # one real source file beside vendored code: kept by the generated
        # rule, dropped by the size rule, with the evidence in the record
        files = [
            "vendor-app/node_modules/react/index.js",
            "vendor-app/node_modules/react/lib/foo.js",
            "vendor-app/src/App.js",
        ]
        result = _evaluate(tmp_path, "vendor-app", "vendor-app", files)
        record = result["record"]
        assert record["reason"] == "too-few-files"
        assert record["generated_ratio"] == 0.667
        assert len(record["generated_files"]) == 2

    def test_lockfile_only_boundary_is_not_generated(self, tmp_path: Path) -> None:
        files = _make_files(tmp_path, "pkg/lock", {
            "Cargo.lock": "# @generated by Cargo\n",
            "Cargo.toml": "[package]\n",
        })
        result = _evaluate(tmp_path, "lock", "pkg/lock", files)
        record = result["record"]
        assert record["reason"] == "too-few-files"
        assert record["generated_files"] == []
        assert record["generated_ratio"] == 0.0
        assert record["non_source_count"] == 2

    def test_counts_leave_out_non_source_files(self, tmp_path: Path) -> None:
        # a 400-line lockfile and a README no longer lift a small boundary
        files = _make_files(tmp_path, "pkg/small", {
            "yarn.lock": "dep@1:\n" * 400,
            "README.md": "# small\n" * 50,
            "package.json": "{}\n",
            "a.js": "x;\n" * 10,
            "b.js": "x;\n" * 10,
            "c.js": "x;\n" * 10,
        })
        record = _evaluate(tmp_path, "small", "pkg/small", files)["record"]
        assert record["files_count"] == 3
        assert record["loc_total"] == 30
        assert record["reason"] == "too-low-loc"

    def test_a_file_listed_twice_counts_once(self, tmp_path: Path) -> None:
        files = _make_files(
            tmp_path, "pkg/dup", {f"f{i}.py": BODY_40 for i in range(3)}
        )
        record = _evaluate(tmp_path, "dup", "pkg/dup", files + files[:1])["record"]
        assert record["files_count"] == 3
        assert record["loc_total"] == 120

    def test_boundary_relative_file_entries(self, tmp_path: Path) -> None:
        _make_files(tmp_path, "pkg/rel", {f"src/f{i}.py": BODY_40 for i in range(3)})
        files = [f"src/f{i}.py" for i in range(3)]
        result = _evaluate(tmp_path, "rel", "pkg/rel", files)
        assert result["kind"] == "kept"
        assert result["record"]["loc_total"] == 120

    def test_rule_order_generated_beats_too_few_files(self, tmp_path: Path) -> None:
        # 2 files (< 3) AND in node_modules/: generated-code reported first
        files = ["pkg/x/node_modules/a.js", "pkg/x/node_modules/b.js"]
        result = _evaluate(tmp_path, "x", "pkg/x", files)
        assert result["kind"] == "dropped"
        assert result["record"]["reason"] == "generated-code"

    def test_rule_order_auto_gen_beats_too_low_loc(self, tmp_path: Path) -> None:
        # 5 files, only 60 LoC, and every one opens with @generated
        body_gen = "// @generated\n" + ("y = 2;\n" * 11)  # 12 LoC each
        files = _make_files(
            tmp_path,
            "pkg/y",
            {f"f{i}.ts": body_gen for i in range(5)},
        )
        result = _evaluate(tmp_path, "y", "pkg/y", files)
        assert result["kind"] == "dropped"
        assert result["record"]["reason"] == "auto-generated-tag"

    def test_custom_thresholds(self, tmp_path: Path) -> None:
        # min_files=1, min_loc=0: a 1-file 1-line boundary passes
        files = _make_files(tmp_path, "pkg/solo", {"f.py": "x = 1\n"})
        result = _evaluate(tmp_path, "solo", "pkg/solo", files, min_files=1, min_loc=0)
        assert result["kind"] == "kept"
        assert result["record"]["loc_total"] == 1


# --------------------------------------------------------------------------
# Signals (presence flags, #598)
# --------------------------------------------------------------------------


class TestSignals:
    def _signals(self, tmp_path: Path, path: str, files: list[str], ci=None) -> dict:
        return mod.collect_signals(files, path, ci or [])

    def test_keys(self, tmp_path: Path) -> None:
        signals = self._signals(tmp_path, "p", ["p/a.py"])
        assert list(signals) == list(mod.SIGNAL_KEYS) + ["large_directory"]

    def test_own_manifest_only_at_the_root(self, tmp_path: Path) -> None:
        signals = self._signals(tmp_path, "p", ["p/package.json"])
        assert signals["own_manifest"] == "p/package.json"
        signals = self._signals(tmp_path, "p", ["p/examples/package.json"])
        assert signals["own_manifest"] is None

    def test_entry_point_shallowest_within_two_folders(self, tmp_path: Path) -> None:
        signals = self._signals(tmp_path, "p", [
            "p/src/deep/er/index.ts", "p/src/pkg/__init__.py", "p/src/index.ts",
        ])
        assert signals["entry_point"] == "p/src/index.ts"
        too_deep = self._signals(tmp_path, "p", ["p/a/b/c/main.go"])
        assert too_deep["entry_point"] is None

    def test_entry_point_names(self, tmp_path: Path) -> None:
        names = ("lib.rs", "main.go", "__init__.py", "Main.java", "mod.ts", "index.tsx")
        for name in names:
            signals = self._signals(tmp_path, "", [f"src/{name}"])
            assert signals["entry_point"] == f"src/{name}"
        assert self._signals(tmp_path, "", ["src/mod.rs"])["entry_point"] is None

    def test_service_definition(self, tmp_path: Path) -> None:
        for name in ("Dockerfile", "deploy/Containerfile", "docker-compose.yml",
                     "Dockerfile.prod", "api.dockerfile", "serverless.yml"):
            signals = self._signals(tmp_path, "s", [f"s/{name}"])
            assert signals["service_definition"] == f"s/{name}"
        assert self._signals(tmp_path, "s", ["s/docker.md"])["service_definition"] is None

    def test_readme_only_at_the_root(self, tmp_path: Path) -> None:
        assert self._signals(tmp_path, "p", ["p/README.md"])["readme"] == "p/README.md"
        assert self._signals(tmp_path, "p", ["p/docs/readme.rst"])["readme"] is None

    @pytest.mark.parametrize("rel", [
        "__tests__/login.ts", "tests/test_x.py", "spec/models/user.rb", "src/a.test.ts",
        "src/b.spec.js", "handler_test.go", "test_parse.py", "user_spec.rb",
        "conftest.py", "jest.config.js", "vitest.config.mts",
    ])
    def test_test_suite(self, tmp_path: Path, rel: str) -> None:
        assert self._signals(tmp_path, "p", [f"p/{rel}"])["test_suite"] == f"p/{rel}"

    @pytest.mark.parametrize(
        "rel", ["src/latest.ts", "src/contest.py", "testing.md", "attest.go"]
    )
    def test_not_test_suite(self, tmp_path: Path, rel: str) -> None:
        assert self._signals(tmp_path, "p", [f"p/{rel}"])["test_suite"] is None

    def test_ci_reference_names_the_whole_path(self, tmp_path: Path) -> None:
        files = ["packages/auth/a.ts"]
        ci = [(".github/workflows/deploy.yml",
               "run: pnpm --filter ./packages/auth test\n")]
        signals = self._signals(tmp_path, "packages/auth", files, ci)
        assert signals["ci_reference"] == ".github/workflows/deploy.yml"
        other = [(".github/workflows/ui.yml", "paths: ['packages/auth-ui/**']\n")]
        signals = self._signals(tmp_path, "packages/auth", files, other)
        assert signals["ci_reference"] is None

    def test_ci_reference_is_null_at_the_root(self, tmp_path: Path) -> None:
        ci = [(".gitlab-ci.yml", "script: make\n")]
        assert self._signals(tmp_path, "", ["a.go"], ci)["ci_reference"] is None

    def test_load_ci_files(self, tmp_path: Path) -> None:
        _write(tmp_path / ".github" / "workflows" / "b.yaml", "b\n")
        _write(tmp_path / ".github" / "workflows" / "a.yml", "a\n")
        _write(tmp_path / ".gitlab-ci.yml", "g\n")
        _write(tmp_path / "docs" / "ci.yml", "not ci\n")
        assert mod.load_ci_files(tmp_path) == [
            (".github/workflows/a.yml", "a\n"),
            (".github/workflows/b.yaml", "b\n"),
            (".gitlab-ci.yml", "g\n"),
        ]

    def test_large_directory_at_fifty_files(self, tmp_path: Path) -> None:
        files = [f"p/f{i}.py" for i in range(50)]
        assert self._signals(tmp_path, "p", files)["large_directory"] is True
        assert self._signals(tmp_path, "p", files[:49])["large_directory"] is False

    def test_filter_reads_ci_files_once_for_every_boundary(
        self, tmp_path: Path
    ) -> None:
        _write(tmp_path / ".github" / "workflows" / "ci.yml",
               "working-directory: services/api\n")
        files = _make_files(
            tmp_path, "services/api", {f"f{i}.py": BODY_40 for i in range(3)}
        )
        result = mod.filter_boundaries(
            [_boundary("api", "services/api", files)], source_root=tmp_path
        )
        signals = result["kept"][0]["signals"]
        assert signals["ci_reference"] == ".github/workflows/ci.yml"


def test_manifest_names_come_from_scan_manifests() -> None:
    scan = _load("skf_scan_manifests_for_disqualify", SCAN_MANIFESTS_PATH)
    assert mod.SCAN_MANIFESTS == SCAN_MANIFESTS_PATH.resolve()
    assert mod.manifest_filenames() == frozenset(scan.MANIFEST_ECOSYSTEMS)
    assert set(mod.scan_manifests_module().IDENTITY_READERS) == set(
        scan.IDENTITY_READERS)


def test_python_floor_is_the_manifest_scanners() -> None:
    """The helper runs skf-scan-manifests.py, which imports tomllib (3.11)."""
    header = SCRIPT_PATH.read_text(encoding="utf-8").splitlines()[:4]
    assert header[1] == '# requires-python = ">=3.11"'
    scanner = SCAN_MANIFESTS_PATH.read_text(encoding="utf-8")
    assert "\nimport tomllib\n" in scanner


def test_filter_without_the_manifest_scanner_exits_1(
    tmp_path: Path, monkeypatch, capsys
) -> None:
    monkeypatch.setattr(mod, "SCAN_MANIFESTS", tmp_path / "skf-scan-manifests.py")
    monkeypatch.setattr(mod, "_SCAN_MODULE", None)
    b_path = tmp_path / "boundaries.json"
    b_path.write_text("[]", encoding="utf-8")
    argv = ["filter", "--boundaries", str(b_path), "--source-root", str(tmp_path)]
    assert mod.main(argv) == 1
    assert "cannot load" in capsys.readouterr().err


@pytest.mark.parametrize(
    "name", ["requirements.txt", "Cargo.toml", "go.mod", "pom.xml", "Package.swift"]
)
def test_every_scanned_manifest_is_an_own_manifest(name: str) -> None:
    signals = mod.collect_signals([f"p/{name}"], "p", [])
    assert signals["own_manifest"] == f"p/{name}"


# --------------------------------------------------------------------------
# The own manifest (the name derive-name takes)
# --------------------------------------------------------------------------


class TestManifest:
    def test_npm_name_and_private_flag(self, tmp_path: Path) -> None:
        files = _make_files(tmp_path, "apps/web", {
            "package.json": '{"name": "@acme/web", "private": true}\n',
            "src/a.ts": BODY_40,
        })
        assert mod.own_manifest(files, "apps/web", tmp_path) == {
            "path": "apps/web/package.json", "ecosystem": "npm",
            "name": "@acme/web", "private": True,
        }

    def test_the_first_manifest_that_names_a_package(self, tmp_path: Path) -> None:
        files = _make_files(tmp_path, "svc", {
            "Gemfile": "source 'https://rubygems.org'\n",
            "package.json": '{"name": "svc"}\n',
            "a.js": BODY_40,
        })
        manifest = mod.own_manifest(files, "svc", tmp_path)
        assert (manifest["path"], manifest["name"]) == ("svc/package.json", "svc")
        signals = _evaluate(tmp_path, "svc", "svc", files)["record"]["signals"]
        assert signals["own_manifest"] == "svc/package.json"

    def test_a_manifest_that_names_no_package(self, tmp_path: Path) -> None:
        files = _make_files(tmp_path, "py", {"requirements.txt": "requests\n"})
        assert mod.own_manifest(files, "py", tmp_path) == {
            "path": "py/requirements.txt", "ecosystem": "python",
            "name": None, "private": None,
        }

    def test_no_manifest_or_an_unreadable_one(self, tmp_path: Path) -> None:
        files = ["x/a.py", "x/sub/package.json"]
        assert mod.own_manifest(files, "x", tmp_path) is None
        assert mod.own_manifest(["x/Cargo.toml"], "x", tmp_path) == {
            "path": "x/Cargo.toml", "ecosystem": "rust",
            "name": None, "private": None,
        }

    @pytest.mark.parametrize(("name", "content", "expected"), [
        ("Cargo.toml", '[package]\nname = "core"\npublish = false\n',
         ("rust", "core", True)),
        ("pyproject.toml", '[project]\nname = "acme-auth"\n',
         ("python", "acme-auth", False)),
        ("go.mod", "module github.com/acme/svc\n",
         ("go", "github.com/acme/svc", None)),
    ], ids=["cargo", "pyproject", "go-mod"])
    def test_ecosystems(
        self, tmp_path: Path, name: str, content: str, expected: tuple
    ) -> None:
        files = _make_files(tmp_path, "u", {name: content})
        manifest = mod.own_manifest(files, "u", tmp_path)
        assert (manifest["ecosystem"], manifest["name"], manifest["private"]) == (
            expected)


# --------------------------------------------------------------------------
# filter_boundaries (multi-boundary aggregation)
# --------------------------------------------------------------------------


class TestFilterBoundaries:
    def test_mixed_outcomes_stats_correct(self, tmp_path: Path) -> None:
        # one kept, one too-few-files, one generated, one too-low-loc
        body_plain = "x = 1\n" * 50
        files_kept = _make_files(
            tmp_path, "pkg/kept", {f"f{i}.py": body_plain for i in range(5)}
        )
        files_tiny = _make_files(
            tmp_path, "pkg/tiny", {f"f{i}.py": body_plain for i in range(2)}
        )
        files_gen = ["pkg/gen/dist/bundle.js"] * 4  # path-based, no files needed
        files_skinny = _make_files(
            tmp_path,
            "pkg/skinny",
            {f"f{i}.py": "x = 1\n" * 10 for i in range(5)},  # 50 LoC total
        )

        result = mod.filter_boundaries(
            [
                _boundary("kept", "pkg/kept", files_kept),
                _boundary("tiny", "pkg/tiny", files_tiny),
                _boundary("gen", "pkg/gen", files_gen),
                _boundary("skinny", "pkg/skinny", files_skinny),
            ],
            source_root=tmp_path,
        )
        assert result["stats"]["kept"] == 1
        assert result["stats"]["dropped"] == 3
        assert result["stats"]["mixed"] == 0
        assert result["stats"]["by_reason"] == {
            "generated-code": 1,
            "too-few-files": 1,
            "too-low-loc": 1,
        }
        kept_names = [r["name"] for r in result["kept"]]
        assert kept_names == ["kept"]
        dropped_reasons = {r["name"]: r["reason"] for r in result["dropped"]}
        assert dropped_reasons == {
            "tiny": "too-few-files",
            "gen": "generated-code",
            "skinny": "too-low-loc",
        }

    def test_mixed_counts_kept_boundaries_with_generated_files(
        self, tmp_path: Path
    ) -> None:
        clean = _make_files(tmp_path, "a", {f"f{i}.py": BODY_40 for i in range(3)})
        mixed = _make_files(tmp_path, "b", {**{f"f{i}.py": BODY_40 for i in range(3)},
                                            "dist/out.js": "x\n"})
        result = mod.filter_boundaries(
            [_boundary("a", "a", clean), _boundary("b", "b", mixed)], source_root=tmp_path,
        )
        assert result["stats"]["kept"] == 2
        assert result["stats"]["mixed"] == 1

    def test_empty_input(self, tmp_path: Path) -> None:
        result = mod.filter_boundaries([], source_root=tmp_path)
        assert result == {
            "kept": [],
            "dropped": [],
            "stats": {"kept": 0, "dropped": 0, "mixed": 0, "by_reason": {}},
        }

    def test_all_dropped_one_reason(self, tmp_path: Path) -> None:
        result = mod.filter_boundaries(
            [
                _boundary("a", "pkg/a", ["pkg/a/node_modules/x.js"]),
                _boundary("b", "pkg/b", ["pkg/b/vendor/y.go"]),
            ],
            source_root=tmp_path,
        )
        assert result["stats"]["by_reason"] == {"generated-code": 2}


# --------------------------------------------------------------------------
# validate_boundaries
# --------------------------------------------------------------------------


class TestValidateBoundaries:
    def test_valid_input(self) -> None:
        raw = [{"name": "a", "path": "p", "files": ["x", "y"]}]
        result = mod.validate_boundaries(raw)
        assert result == [{"name": "a", "path": "p", "files": ["x", "y"]}]

    def test_backslash_normalized(self) -> None:
        raw = [{"name": "a", "path": r"pkg\a", "files": [r"src\App.tsx"]}]
        result = mod.validate_boundaries(raw)
        assert result[0]["path"] == "pkg/a"
        assert result[0]["files"] == ["src/App.tsx"]

    def test_not_array_raises(self) -> None:
        with pytest.raises(ValueError, match="must be a JSON array"):
            mod.validate_boundaries({"name": "a"})

    def test_entry_not_object_raises(self) -> None:
        with pytest.raises(ValueError, match="not an object"):
            mod.validate_boundaries(["not an object"])

    def test_missing_name_raises(self) -> None:
        with pytest.raises(ValueError, match="required `name`"):
            mod.validate_boundaries([{"path": "p", "files": []}])

    def test_empty_name_raises(self) -> None:
        with pytest.raises(ValueError, match="required `name`"):
            mod.validate_boundaries([{"name": "", "path": "p", "files": []}])

    def test_missing_path_raises(self) -> None:
        with pytest.raises(ValueError, match="required `path`"):
            mod.validate_boundaries([{"name": "a", "files": []}])

    def test_missing_files_are_listed_later(self) -> None:
        """Without `files` the helper lists the boundary's folder itself."""
        result = mod.validate_boundaries([{"name": "a", "path": r"pkg\a"}])
        assert result == [{"name": "a", "path": "pkg/a", "files": None}]

    def test_files_not_array_raises(self) -> None:
        with pytest.raises(ValueError, match="`files` value that is not an array"):
            mod.validate_boundaries([{"name": "a", "path": "p", "files": "x"}])

    def test_file_entry_not_string_raises(self) -> None:
        with pytest.raises(ValueError, match="not a string"):
            mod.validate_boundaries(
                [{"name": "a", "path": "p", "files": ["x", 42]}]
            )


# --------------------------------------------------------------------------
# CLI integration
# --------------------------------------------------------------------------


def _run_cli(
    *args: str, stdin_text: str | None = None
) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPT_PATH), *args],
        capture_output=True,
        text=True,
        input=stdin_text,
        check=False,
    )


class TestCli:
    def test_filter_from_file(self, tmp_path: Path) -> None:
        # one kept + one dropped
        body = "x = 1\n" * 50
        files_kept = _make_files(
            tmp_path, "pkg/kept", {f"f{i}.py": body for i in range(5)}
        )
        boundaries = [
            _boundary("kept", "pkg/kept", files_kept),
            _boundary("tiny", "pkg/tiny", ["pkg/tiny/a.py", "pkg/tiny/b.py"]),
        ]
        b_path = tmp_path / "boundaries.json"
        b_path.write_text(json.dumps(boundaries), encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload["stats"]["kept"] == 1
        assert payload["stats"]["dropped"] == 1
        assert payload["stats"]["by_reason"] == {"too-few-files": 1}
        assert payload["kept"][0]["name"] == "kept"
        assert payload["dropped"][0]["reason"] == "too-few-files"

    def test_filter_from_stdin(self, tmp_path: Path) -> None:
        body = "x = 1\n" * 50
        files = _make_files(
            tmp_path, "pkg/auth", {f"f{i}.py": body for i in range(4)}
        )
        boundaries = [_boundary("auth", "pkg/auth", files)]
        stdin_text = json.dumps(boundaries)
        result = _run_cli(
            "filter",
            "--boundaries",
            "-",
            "--source-root",
            str(tmp_path),
            stdin_text=stdin_text,
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload["stats"]["kept"] == 1
        assert payload["kept"][0]["files_count"] == 4

    def test_filter_empty_input_succeeds(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text("[]", encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload == {
            "kept": [],
            "dropped": [],
            "stats": {"kept": 0, "dropped": 0, "mixed": 0, "by_reason": {}},
        }

    def test_filter_custom_thresholds(self, tmp_path: Path) -> None:
        # 1-file, 1-line boundary normally drops as too-few-files; relax
        # thresholds via flags
        files = _make_files(tmp_path, "pkg/solo", {"f.py": "x = 1\n"})
        boundaries = [_boundary("solo", "pkg/solo", files)]
        b_path = tmp_path / "boundaries.json"
        b_path.write_text(json.dumps(boundaries), encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
            "--min-files",
            "1",
            "--min-loc",
            "0",
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload["stats"]["kept"] == 1

    def test_filter_generated_code_via_stdin(self, tmp_path: Path) -> None:
        boundaries = [
            _boundary(
                "vendored",
                "pkg/v",
                [
                    "pkg/v/node_modules/react/index.js",
                    "pkg/v/node_modules/react/cjs/react.js",
                ],
            ),
        ]
        result = _run_cli(
            "filter",
            "--boundaries",
            "-",
            "--source-root",
            str(tmp_path),
            stdin_text=json.dumps(boundaries),
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload["stats"]["by_reason"] == {"generated-code": 1}
        assert payload["dropped"][0]["context"]["matched_segment"] == "node_modules/"

    def test_filter_mixed_boundary_kept_via_stdin(self, tmp_path: Path) -> None:
        body_gen = "// @generated by codegen\n" + ("x = 1;\n" * 50)
        body_plain = "x = 1;\n" * 50
        files = _make_files(
            tmp_path,
            "pkg/codegen",
            {
                "schema.ts": body_gen,
                "model.ts": body_plain,
                "service.ts": body_plain,
                "client.ts": body_plain,
            },
        )
        boundaries = [_boundary("codegen", "pkg/codegen", files)]
        result = _run_cli(
            "filter",
            "--boundaries",
            "-",
            "--source-root",
            str(tmp_path),
            stdin_text=json.dumps(boundaries),
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload["stats"] == {"kept": 1, "dropped": 0, "mixed": 1, "by_reason": {}}
        assert payload["kept"][0]["generated_files"][0]["reason"] == "auto-generated-tag"

    def test_filter_missing_file_exits_1(self, tmp_path: Path) -> None:
        result = _run_cli(
            "filter",
            "--boundaries",
            str(tmp_path / "missing.json"),
            "--source-root",
            str(tmp_path),
        )
        assert result.returncode == 1
        assert "not found" in result.stderr

    def test_filter_malformed_json_exits_1(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text("{not json", encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
        )
        assert result.returncode == 1
        assert "malformed JSON" in result.stderr

    def test_filter_missing_required_field_exits_1(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text(
            json.dumps([{"name": "a", "files": []}]), encoding="utf-8"
        )
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
        )
        assert result.returncode == 1
        assert "path" in result.stderr

    def test_filter_negative_min_files_exits_1(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text("[]", encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
            "--min-files",
            "-1",
        )
        assert result.returncode == 1
        assert "min-files" in result.stderr

    def test_filter_negative_min_loc_exits_1(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text("[]", encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
            "--min-loc",
            "-5",
        )
        assert result.returncode == 1
        assert "min-loc" in result.stderr

    def test_filter_bad_source_root_exits_1(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text("[]", encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path / "does-not-exist"),
        )
        assert result.returncode == 1
        assert "source-root" in result.stderr


# --------------------------------------------------------------------------
# The prose that runs the helper
# --------------------------------------------------------------------------


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def test_identify_units_leaves_the_judgment_to_the_model() -> None:
    text = _read(IDENTIFY_UNITS)
    assert "authoritative" not in text, "a script drop reason is evidence, not a verdict"
    for field in ("generated_files", "generated_ratio", "signals", "stats.mixed",
                  "passes_with_generated", "manifest.name", "manifest.private"):
        assert field in text, field
    assert "filter --boundaries -" in text
    # Step B may restore any drop the flagged files caused, never a too-small one
    restore = text.split("**A drop the flagged files caused:**", 1)[1].split("\n", 1)[0]
    for reason in ("generated-code", "auto-generated-tag", "too-few-files", "too-low-loc"):
        assert f"`{reason}`" in restore, reason
    assert "`passes_with_generated` is true" in restore
    # The record carries the own manifest: no second scan and join by hand
    assert "scanManifests" not in text


def test_heuristics_state_the_script_thresholds() -> None:
    text = _read(HEURISTICS)
    phrase = f"Fewer than {mod.MIN_FILES} source files or {mod.MIN_LOC} lines of code"
    assert phrase in text
    assert "every source file" in text
    assert "`com/acme/build/`" in text, "an output folder name deeper down is source"


def test_map_and_detect_reads_exports_by_eye_where_no_recipe_runs() -> None:
    """The runner reads no Java, Kotlin or Swift: exit 0 is no T1 result there.
    map-and-detect and the [D] file map each unit through map-unit-exports.md."""
    assert "execute {unitExportsFile}" in _read(MAP_AND_DETECT)
    text = _read(UNIT_EXPORTS)
    branch = text.split("**No recipe for the unit's language:**", 1)[1]
    branch = branch.split("\n", 1)[0]
    for needle in ("`files_in_scope` is 0", "`files_without_recipes`", "Java",
                   "whatever its exit code", '`strategy_used: "source-read"`',
                   '`confidence: "T1-low"`'):
        assert needle in branch, needle
    for field in ("entry_point_diff.extraction_gaps[]", "file_issues[]"):
        assert field in text, field
    assert "`files_count` is the unit's file count the loading file gave" in text
    assert "its file count from Identified Units" in _read(MAP_AND_DETECT)
    assert "`files_count` is the runner's `files_in_scope`" not in text


def test_composites_are_decided_after_the_import_graph_and_reach_the_brief() -> None:
    """#602: the composite promise has a carrier from map-and-detect to the brief."""
    identify = _read(IDENTIFY_UNITS)
    assert "composite merges are proposed in map-and-detect" in identify
    assert "confirmed_composites" not in identify
    mapping = _read(MAP_AND_DETECT)
    assert mapping.index("### 3. Map Import Graph") < mapping.index(
        "### 5. Decide Composites")
    assert "confirmed_composites: [{list of approved composites: {name, " \
           "constituents: [{name, path}], heuristic}}]" in mapping
    briefs = _read(GENERATE_BRIEFS)
    include = next(line for line in briefs.splitlines()
                   if line.startswith("| scope.include |"))
    assert "`confirmed_composites` entry" in include
    assert "`<path>/**` for every constituent path" in include


# --------------------------------------------------------------------------
# The helper lists each boundary's files (the wave-3 determinism-3 finding)
# --------------------------------------------------------------------------


DETECT_LANGUAGE_PATH = REPO_ROOT / "src" / "shared" / "scripts" / "skf-detect-language.py"
SOURCE = ("x = 1\n" * 40).encode("utf-8")


def _tree(root: Path, files: dict[str, bytes]) -> None:
    for rel, data in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)


def _git(root: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=root, check=True, capture_output=True, timeout=60)


MONOREPO = {
    "packages/auth/package.json": b'{"name": "@acme/auth"}\n',
    "packages/auth/src/a.ts": SOURCE,
    "packages/auth/src/b.ts": SOURCE,
    "packages/auth/src/c.ts": SOURCE,
    "packages/auth/node_modules/dep/index.js": SOURCE,
    "packages/auth/.cache/x.ts": SOURCE,
    "packages/auth/__pycache__/m.pyc": b"\x00",
    "packages/ui/src/view.ts": SOURCE,
    ".gitignore": b"node_modules/\n",
}


class TestListing:
    @pytest.mark.skipif(shutil.which("git") is None, reason="git is not installed")
    def test_git_lists_the_boundary_and_ignored_files_stay_out(self, tmp_path: Path) -> None:
        _tree(tmp_path, MONOREPO)
        _tree(tmp_path, {"packages/auth/src/new.ts": SOURCE})  # untracked, not ignored
        _git(tmp_path, "init", "-q")
        files = mod.list_source_files(tmp_path)
        assert mod.list_boundary_files(files, "packages/auth") == [
            "packages/auth/__pycache__/m.pyc",  # not ignored here: git lists it
            "packages/auth/package.json",
            "packages/auth/src/a.ts", "packages/auth/src/b.ts", "packages/auth/src/c.ts",
            "packages/auth/src/new.ts",
        ]
        assert mod.list_boundary_files(files, ".") == files
        assert ".gitignore" not in files, "hidden entries are left out"

    def test_a_folder_outside_a_work_tree_is_walked(self, tmp_path: Path, monkeypatch) -> None:
        _tree(tmp_path, MONOREPO)
        monkeypatch.setattr(mod, "_git_files", lambda root: None)
        files = mod.list_boundary_files(mod.list_source_files(tmp_path), "packages/auth/")
        assert files == ["packages/auth/package.json", "packages/auth/src/a.ts",
                         "packages/auth/src/b.ts", "packages/auth/src/c.ts"]

    def test_the_cli_lists_writes_the_tree_files_and_names_them(self, tmp_path: Path) -> None:
        root = tmp_path / "src-root"
        _tree(root, MONOREPO)
        trees = tmp_path / "run" / "unit-trees" / "1"
        boundaries = [{"name": "auth", "path": "packages/auth"}, {"name": "ui", "path": "packages/ui"}]
        result = _run_cli("filter", "--boundaries", "-", "--source-root", str(root),
                          "--tree-dir", str(trees), stdin_text=json.dumps(boundaries))
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        [auth] = payload["kept"]
        [ui] = payload["dropped"]
        assert (auth["name"], auth["files_count"], ui["reason"]) == ("auth", 3, "too-few-files")
        assert Path(auth["tree_file"]).as_posix() == (trees / "boundary-1.txt").resolve().as_posix()
        assert Path(ui["tree_file"]).as_posix() == (trees / "boundary-2.txt").resolve().as_posix()
        listed = Path(auth["tree_file"]).read_bytes().decode("utf-8").splitlines()
        assert "packages/auth/src/a.ts" in listed and "packages/auth/package.json" in listed
        assert not any("node_modules" in line or "/." in line for line in listed)
        # identify-units hands that file to the language helper as the unit's tree
        language = subprocess.run([sys.executable, str(DETECT_LANGUAGE_PATH), "--tree-file", auth["tree_file"]],
                                  capture_output=True, timeout=60)
        assert language.returncode == 0, language.stderr
        assert json.loads(language.stdout)["language"] == "javascript"

    def test_given_files_are_written_too(self, tmp_path: Path) -> None:
        _tree(tmp_path, {"pkg/a.py": SOURCE})
        result = _run_cli("filter", "--boundaries", "-", "--source-root", str(tmp_path),
                          "--tree-dir", str(tmp_path / "trees"),
                          stdin_text=json.dumps([{"name": "pkg", "path": "pkg", "files": ["pkg/a.py"]}]))
        assert result.returncode == 0, result.stderr
        [record] = json.loads(result.stdout)["dropped"]
        assert Path(record["tree_file"]).read_bytes() == b"pkg/a.py\n"

    def test_without_tree_dir_no_record_names_a_tree_file(self, tmp_path: Path) -> None:
        _tree(tmp_path, MONOREPO)
        result = _run_cli("filter", "--boundaries", "-", "--source-root", str(tmp_path),
                          stdin_text=json.dumps([{"name": "auth", "path": "packages/auth"}]))
        assert result.returncode == 0, result.stderr
        assert "tree_file" not in json.loads(result.stdout)["kept"][0]

    def test_a_boundary_path_that_is_no_folder_exits_1(self, tmp_path: Path) -> None:
        result = _run_cli("filter", "--boundaries", "-", "--source-root", str(tmp_path),
                          stdin_text=json.dumps([{"name": "x", "path": "packages/missing"}]))
        assert result.returncode == 1
        assert "packages/missing is not a folder under the source root" in result.stderr

    @pytest.mark.parametrize("path", ["./packages/auth", "packages/auth/", "packages/./auth",
                                      "packages//auth", r"packages\auth"],
                             ids=["dot-slash", "trailing-slash", "inner-dot", "double-slash", "backslash"])
    def test_an_unnormalized_boundary_path_lists_the_same_files(self, tmp_path: Path, path: str) -> None:
        """A path the model types as `./packages/auth` is the folder `packages/auth`."""
        _tree(tmp_path, MONOREPO)
        result = _run_cli("filter", "--boundaries", "-", "--source-root", str(tmp_path),
                          stdin_text=json.dumps([{"name": "a", "path": "packages/auth"},
                                                 {"name": "b", "path": path}]))
        assert result.returncode == 0, result.stderr
        kept = json.loads(result.stdout)["kept"]
        assert [(r["path"], r["files_count"]) for r in kept] == [("packages/auth", 3), ("packages/auth", 3)]

    @pytest.mark.parametrize("path", ["", ".", "./", "pkg/.."], ids=["empty", "dot", "dot-slash", "up-to-root"])
    def test_a_root_path_reads_as_dot(self, path: str) -> None:
        [entry] = mod.validate_boundaries([{"name": "a", "path": path}])
        assert entry["path"] == "."

    @pytest.mark.parametrize("path", ["..", "../sibling", "pkg/../../x", "/abs/pkg", "C:/pkg"],
                             ids=["parent", "sibling", "escapes", "absolute", "drive"])
    def test_a_path_that_leaves_the_source_root_exits_1(self, tmp_path: Path, path: str) -> None:
        result = _run_cli("filter", "--boundaries", "-", "--source-root", str(tmp_path),
                          stdin_text=json.dumps([{"name": "x", "path": path, "files": []}]))
        assert result.returncode == 1
        assert "is not a folder below the source root" in result.stderr

    @pytest.mark.skipif(shutil.which("git") is None, reason="git is not installed")
    def test_a_folder_the_outer_work_tree_ignores_is_walked(self, tmp_path: Path) -> None:
        """An extracted tarball under an ignored vendor/ is no empty unit."""
        _tree(tmp_path, {".gitignore": b"vendor/\n", "app.py": SOURCE})
        _git(tmp_path, "init", "-q")
        root = tmp_path / "vendor" / "lib"
        _tree(root, MONOREPO)
        files = mod.list_boundary_files(mod.list_source_files(root), "packages/auth")
        assert files == ["packages/auth/package.json", "packages/auth/src/a.ts",
                         "packages/auth/src/b.ts", "packages/auth/src/c.ts"]

    def test_a_path_git_lists_twice_counts_once(self, tmp_path: Path, monkeypatch) -> None:
        """git ls-files prints an unmerged path once per stage."""
        _tree(tmp_path, {"pkg/a.py": SOURCE, "pkg/b.py": SOURCE})
        monkeypatch.setattr(mod, "_git_files", lambda root: ["pkg/b.py", "pkg/a.py", "pkg/b.py", "pkg/b.py"])
        assert mod.list_source_files(tmp_path) == ["pkg/a.py", "pkg/b.py"]

    def test_a_name_that_is_not_utf8_keeps_the_tree_file_utf8(self, tmp_path: Path) -> None:
        name = b"pkg/caf\xe9.py".decode("utf-8", errors="surrogateescape")
        tree = mod.write_tree_file(tmp_path, 1, ["pkg/a.py", name])
        assert tree.read_bytes() == b"pkg/a.py\npkg/caf?.py\n"


def test_identify_units_lets_the_helper_list_the_files() -> None:
    """No file list passes through the model: Step A sends name and path, and
    section 4 hands the record's tree_file to the language helper."""
    text = _read(IDENTIFY_UNITS)
    assert '--source-root "{scan_root}" --tree-dir "{run_dir}/unit-trees/{i}"' in text
    assert '"files": [' not in text
    assert 'echo \'{"tree"' not in text
    assert 'uv run {detectLanguageHelper} --tree-file "{the unit\'s tree_file}"' in text
    assert "project_paths[0]" not in text, "each unit is named under its own project path"
