#!/usr/bin/env python3
"""Tests for skf-disqualify-candidates.py.

Covers:
  - find_generated_segment: node_modules/, vendor/, dist/, build/,
    __pycache__/, .next/, target/, .gradle/ at root and nested
  - has_auto_generated_marker: @generated / // GENERATED CODE /
    # AUTOGENERATED / <!-- generated --> within first 10 lines
  - count_nonblank_lines: empty file, whitespace-only lines, trailing
    newline, mix of content + blanks
  - evaluate_boundary: rule order (generated-code > auto-gen > too-few-files
    > too-low-loc), kept records
  - filter_boundaries: stats by_reason, kept/dropped partitions, empty
    input
  - validate_boundaries: missing name/path/files, wrong types
  - CLI: file input, stdin (-) piping, exit codes for malformed input
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).parent.parent
SCRIPT_PATH = (
    REPO_ROOT / "src" / "shared" / "scripts" / "skf-disqualify-candidates.py"
)

spec = importlib.util.spec_from_file_location(
    "skf_disqualify_candidates", SCRIPT_PATH
)
mod = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(mod)


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------


def _write(path: Path, content: str = "") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content.encode("utf-8"))
    return path


def _boundary(name: str, path: str, files: list[str]) -> dict:
    return {"name": name, "path": path, "files": files}


def _make_files(
    source_root: Path, boundary_path: str, file_specs: dict[str, str]
) -> list[str]:
    """Materialize <source_root>/<boundary_path>/<file_rel> for each entry
    in file_specs and return the list of `files[]` paths in source-root-
    relative form (matching how scan-project would record them).
    """
    files: list[str] = []
    for rel, content in file_specs.items():
        full = source_root / boundary_path / rel
        _write(full, content)
        # source-root-relative form, forward-slash for cross-platform JSON
        files.append((Path(boundary_path) / rel).as_posix())
    return files


# --------------------------------------------------------------------------
# find_generated_segment
# --------------------------------------------------------------------------


class TestFindGeneratedSegment:
    def test_node_modules_at_root(self) -> None:
        assert mod.find_generated_segment("node_modules/react/index.js") == "node_modules/"

    def test_node_modules_nested(self) -> None:
        assert (
            mod.find_generated_segment("packages/ui/node_modules/foo/index.js")
            == "node_modules/"
        )

    def test_vendor(self) -> None:
        assert mod.find_generated_segment("vendor/lib.go") == "vendor/"

    def test_dist(self) -> None:
        assert mod.find_generated_segment("dist/bundle.js") == "dist/"

    def test_build(self) -> None:
        assert mod.find_generated_segment("build/output.so") == "build/"

    def test_pycache(self) -> None:
        assert (
            mod.find_generated_segment("src/__pycache__/foo.cpython-310.pyc")
            == "__pycache__/"
        )

    def test_next(self) -> None:
        assert mod.find_generated_segment(".next/server.js") == ".next/"

    def test_target_rust(self) -> None:
        assert mod.find_generated_segment("target/debug/foo") == "target/"

    def test_gradle(self) -> None:
        assert mod.find_generated_segment(".gradle/caches/x.jar") == ".gradle/"

    def test_clean_path_returns_none(self) -> None:
        assert mod.find_generated_segment("src/main.py") is None

    def test_backslash_normalized(self) -> None:
        # Windows-style separators get folded to forward-slash before match
        assert (
            mod.find_generated_segment(r"packages\ui\node_modules\foo.js")
            == "node_modules/"
        )

    def test_substring_alone_does_not_match(self) -> None:
        # `dist` (no trailing slash → no directory segment) shouldn't match
        # via a filename like `redistribute.py`
        assert mod.find_generated_segment("src/redistribute.py") is None


# --------------------------------------------------------------------------
# has_auto_generated_marker
# --------------------------------------------------------------------------


class TestAutoGeneratedMarker:
    def test_at_generated_line_1(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "# @generated\nprint('hi')\n")
        assert mod.has_auto_generated_marker(f) == "@generated"

    def test_generated_code_comment(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.ts", "// GENERATED CODE — DO NOT EDIT\nexport {}\n")
        assert mod.has_auto_generated_marker(f) == "// generated code"

    def test_autogenerated_python_comment(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "# AUTOGENERATED FILE\nx = 1\n")
        assert mod.has_auto_generated_marker(f) == "# autogenerated"

    def test_html_comment(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.html", "<!-- generated -->\n<html></html>\n")
        assert mod.has_auto_generated_marker(f) == "<!-- generated -->"

    def test_case_insensitive(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "# @Generated by tool\nx = 1\n")
        assert mod.has_auto_generated_marker(f) == "@generated"

    def test_within_first_10_lines(self, tmp_path: Path) -> None:
        # marker at line 10 — still within scan window
        body = "\n".join([f"# line {i}" for i in range(1, 10)] + ["@generated"]) + "\n"
        f = _write(tmp_path / "f.py", body)
        assert mod.has_auto_generated_marker(f) == "@generated"

    def test_beyond_first_10_lines_misses(self, tmp_path: Path) -> None:
        # marker at line 12 — outside scan window
        body = "\n".join(
            [f"# line {i}" for i in range(1, 12)] + ["// GENERATED CODE"]
        ) + "\n"
        f = _write(tmp_path / "f.py", body)
        assert mod.has_auto_generated_marker(f) is None

    def test_no_marker(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "def foo():\n    return 1\n")
        assert mod.has_auto_generated_marker(f) is None

    def test_unreadable_file_returns_none(self, tmp_path: Path) -> None:
        # nonexistent file — should silently return None (header scan is
        # opportunistic, not authoritative)
        assert mod.has_auto_generated_marker(tmp_path / "missing.py") is None


# --------------------------------------------------------------------------
# count_nonblank_lines
# --------------------------------------------------------------------------


class TestCountNonblankLines:
    def test_empty_file(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "")
        assert mod.count_nonblank_lines(f) == 0

    def test_only_whitespace(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "   \n\t\n  \n")
        assert mod.count_nonblank_lines(f) == 0

    def test_mixed_content_and_blanks(self, tmp_path: Path) -> None:
        f = _write(
            tmp_path / "f.py",
            "import os\n"   # 1
            "\n"            # blank
            "def foo():\n"  # 2
            "   \n"         # whitespace-only → blank
            "    return 1\n"  # 3
        )
        assert mod.count_nonblank_lines(f) == 3

    def test_trailing_newline(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "x = 1\ny = 2\n")
        assert mod.count_nonblank_lines(f) == 2

    def test_no_trailing_newline(self, tmp_path: Path) -> None:
        f = _write(tmp_path / "f.py", "x = 1\ny = 2")  # no trailing \n
        assert mod.count_nonblank_lines(f) == 2

    def test_missing_file_returns_zero(self, tmp_path: Path) -> None:
        assert mod.count_nonblank_lines(tmp_path / "missing.py") == 0


# --------------------------------------------------------------------------
# evaluate_boundary
# --------------------------------------------------------------------------


class TestEvaluateBoundary:
    def test_kept_boundary(self, tmp_path: Path) -> None:
        # 5 files * 30 non-blank lines = 150 LoC → passes both thresholds
        body = ("x = 1\n" * 30)
        files = _make_files(
            tmp_path,
            "pkg/auth",
            {f"file{i}.py": body for i in range(5)},
        )
        result = mod.evaluate_boundary(
            _boundary("auth", "pkg/auth", files),
            source_root=tmp_path,
        )
        assert result["kind"] == "kept"
        assert result["record"]["name"] == "auth"
        assert result["record"]["path"] == "pkg/auth"
        assert result["record"]["files_count"] == 5
        assert result["record"]["loc_total"] == 150

    def test_dropped_too_few_files(self, tmp_path: Path) -> None:
        body = "x = 1\n" * 60  # plenty of LoC
        files = _make_files(
            tmp_path,
            "pkg/tiny",
            {f"f{i}.py": body for i in range(2)},
        )
        result = mod.evaluate_boundary(
            _boundary("tiny", "pkg/tiny", files),
            source_root=tmp_path,
        )
        assert result["kind"] == "dropped"
        assert result["record"]["reason"] == "too-few-files"
        assert result["record"]["context"]["files_count"] == 2
        assert result["record"]["context"]["threshold"] == 3

    def test_dropped_too_low_loc(self, tmp_path: Path) -> None:
        # 5 files * 12 lines = 60 LoC → below 100 threshold
        body = "x = 1\n" * 12
        files = _make_files(
            tmp_path,
            "pkg/skinny",
            {f"f{i}.py": body for i in range(5)},
        )
        result = mod.evaluate_boundary(
            _boundary("skinny", "pkg/skinny", files),
            source_root=tmp_path,
        )
        assert result["kind"] == "dropped"
        assert result["record"]["reason"] == "too-low-loc"
        assert result["record"]["context"]["files_count"] == 5
        assert result["record"]["context"]["loc_total"] == 60

    def test_dropped_generated_code_node_modules(self, tmp_path: Path) -> None:
        # files inside node_modules/ → drop immediately, no LoC needed
        files = [
            "vendor-app/node_modules/react/index.js",
            "vendor-app/node_modules/react/lib/foo.js",
            "vendor-app/src/App.js",
        ]
        # don't even need to materialize — the path check is string-only
        result = mod.evaluate_boundary(
            _boundary("vendor-app", "vendor-app", files),
            source_root=tmp_path,
        )
        assert result["kind"] == "dropped"
        assert result["record"]["reason"] == "generated-code"
        assert result["record"]["context"]["matched_segment"] == "node_modules/"
        assert "node_modules/" in result["record"]["context"]["first_match"]

    def test_dropped_auto_generated_tag(self, tmp_path: Path) -> None:
        # 5 files, plenty of LoC, but one has @generated → drop
        body_plain = "x = 1\n" * 50
        body_gen = "# @generated by codegen\n" + ("y = 2\n" * 50)
        files = _make_files(
            tmp_path,
            "pkg/protobuf",
            {
                "schema.py": body_gen,
                "model_a.py": body_plain,
                "model_b.py": body_plain,
                "model_c.py": body_plain,
            },
        )
        result = mod.evaluate_boundary(
            _boundary("protobuf", "pkg/protobuf", files),
            source_root=tmp_path,
        )
        assert result["kind"] == "dropped"
        assert result["record"]["reason"] == "auto-generated-tag"
        assert result["record"]["context"]["matched_sentinel"] == "@generated"

    def test_rule_order_generated_beats_too_few_files(self, tmp_path: Path) -> None:
        # 2 files (< 3) AND in node_modules/ → generated-code reported first
        files = ["pkg/x/node_modules/a.js", "pkg/x/node_modules/b.js"]
        result = mod.evaluate_boundary(
            _boundary("x", "pkg/x", files),
            source_root=tmp_path,
        )
        assert result["kind"] == "dropped"
        assert result["record"]["reason"] == "generated-code"

    def test_rule_order_auto_gen_beats_too_low_loc(self, tmp_path: Path) -> None:
        # 5 files, only 60 LoC, AND first file has @generated → auto-gen wins
        body_gen = "// @generated\n" + ("y = 2;\n" * 11)  # 12 LoC each
        files = _make_files(
            tmp_path,
            "pkg/y",
            {f"f{i}.ts": body_gen for i in range(5)},
        )
        result = mod.evaluate_boundary(
            _boundary("y", "pkg/y", files),
            source_root=tmp_path,
        )
        assert result["kind"] == "dropped"
        assert result["record"]["reason"] == "auto-generated-tag"

    def test_custom_thresholds(self, tmp_path: Path) -> None:
        # set min_files=1, min_loc=0 → a 1-file 1-line boundary passes
        files = _make_files(tmp_path, "pkg/solo", {"f.py": "x = 1\n"})
        result = mod.evaluate_boundary(
            _boundary("solo", "pkg/solo", files),
            source_root=tmp_path,
            min_files=1,
            min_loc=0,
        )
        assert result["kind"] == "kept"
        assert result["record"]["loc_total"] == 1


# --------------------------------------------------------------------------
# filter_boundaries (multi-boundary aggregation)
# --------------------------------------------------------------------------


class TestFilterBoundaries:
    def test_mixed_outcomes_stats_correct(self, tmp_path: Path) -> None:
        # one kept, one too-few-files, one generated, one too-low-loc
        body_plain = "x = 1\n" * 50
        files_kept = _make_files(
            tmp_path, "pkg/kept", {f"f{i}.py": body_plain for i in range(5)}
        )
        files_tiny = _make_files(
            tmp_path, "pkg/tiny", {f"f{i}.py": body_plain for i in range(2)}
        )
        files_gen = ["pkg/gen/dist/bundle.js"] * 4  # path-based, no files needed
        files_skinny = _make_files(
            tmp_path,
            "pkg/skinny",
            {f"f{i}.py": "x = 1\n" * 10 for i in range(5)},  # 50 LoC total
        )

        result = mod.filter_boundaries(
            [
                _boundary("kept", "pkg/kept", files_kept),
                _boundary("tiny", "pkg/tiny", files_tiny),
                _boundary("gen", "pkg/gen", files_gen),
                _boundary("skinny", "pkg/skinny", files_skinny),
            ],
            source_root=tmp_path,
        )
        assert result["stats"]["kept"] == 1
        assert result["stats"]["dropped"] == 3
        assert result["stats"]["by_reason"] == {
            "generated-code": 1,
            "too-few-files": 1,
            "too-low-loc": 1,
        }
        kept_names = [r["name"] for r in result["kept"]]
        assert kept_names == ["kept"]
        dropped_reasons = {r["name"]: r["reason"] for r in result["dropped"]}
        assert dropped_reasons == {
            "tiny": "too-few-files",
            "gen": "generated-code",
            "skinny": "too-low-loc",
        }

    def test_empty_input(self, tmp_path: Path) -> None:
        result = mod.filter_boundaries([], source_root=tmp_path)
        assert result == {
            "kept": [],
            "dropped": [],
            "stats": {"kept": 0, "dropped": 0, "by_reason": {}},
        }

    def test_all_dropped_one_reason(self, tmp_path: Path) -> None:
        result = mod.filter_boundaries(
            [
                _boundary("a", "pkg/a", ["pkg/a/node_modules/x.js"]),
                _boundary("b", "pkg/b", ["pkg/b/vendor/y.go"]),
            ],
            source_root=tmp_path,
        )
        assert result["stats"]["by_reason"] == {"generated-code": 2}


# --------------------------------------------------------------------------
# validate_boundaries
# --------------------------------------------------------------------------


class TestValidateBoundaries:
    def test_valid_input(self) -> None:
        raw = [{"name": "a", "path": "p", "files": ["x", "y"]}]
        result = mod.validate_boundaries(raw)
        assert result == [{"name": "a", "path": "p", "files": ["x", "y"]}]

    def test_backslash_normalized(self) -> None:
        raw = [{"name": "a", "path": r"pkg\a", "files": [r"src\App.tsx"]}]
        result = mod.validate_boundaries(raw)
        assert result[0]["path"] == "pkg/a"
        assert result[0]["files"] == ["src/App.tsx"]

    def test_not_array_raises(self) -> None:
        import pytest

        with pytest.raises(ValueError, match="must be a JSON array"):
            mod.validate_boundaries({"name": "a"})

    def test_entry_not_object_raises(self) -> None:
        import pytest

        with pytest.raises(ValueError, match="not an object"):
            mod.validate_boundaries(["not an object"])

    def test_missing_name_raises(self) -> None:
        import pytest

        with pytest.raises(ValueError, match="required `name`"):
            mod.validate_boundaries([{"path": "p", "files": []}])

    def test_empty_name_raises(self) -> None:
        import pytest

        with pytest.raises(ValueError, match="required `name`"):
            mod.validate_boundaries([{"name": "", "path": "p", "files": []}])

    def test_missing_path_raises(self) -> None:
        import pytest

        with pytest.raises(ValueError, match="required `path`"):
            mod.validate_boundaries([{"name": "a", "files": []}])

    def test_missing_files_raises(self) -> None:
        import pytest

        with pytest.raises(ValueError, match="required `files` array"):
            mod.validate_boundaries([{"name": "a", "path": "p"}])

    def test_files_not_array_raises(self) -> None:
        import pytest

        with pytest.raises(ValueError, match="required `files` array"):
            mod.validate_boundaries([{"name": "a", "path": "p", "files": "x"}])

    def test_file_entry_not_string_raises(self) -> None:
        import pytest

        with pytest.raises(ValueError, match="not a string"):
            mod.validate_boundaries(
                [{"name": "a", "path": "p", "files": ["x", 42]}]
            )


# --------------------------------------------------------------------------
# CLI integration
# --------------------------------------------------------------------------


def _run_cli(
    *args: str, stdin_text: str | None = None
) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPT_PATH), *args],
        capture_output=True,
        text=True,
        input=stdin_text,
        check=False,
    )


class TestCli:
    def test_filter_from_file(self, tmp_path: Path) -> None:
        # one kept + one dropped
        body = "x = 1\n" * 50
        files_kept = _make_files(
            tmp_path, "pkg/kept", {f"f{i}.py": body for i in range(5)}
        )
        boundaries = [
            _boundary("kept", "pkg/kept", files_kept),
            _boundary("tiny", "pkg/tiny", ["pkg/tiny/a.py", "pkg/tiny/b.py"]),
        ]
        b_path = tmp_path / "boundaries.json"
        b_path.write_text(json.dumps(boundaries), encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload["stats"]["kept"] == 1
        assert payload["stats"]["dropped"] == 1
        assert payload["stats"]["by_reason"] == {"too-few-files": 1}
        assert payload["kept"][0]["name"] == "kept"
        assert payload["dropped"][0]["reason"] == "too-few-files"

    def test_filter_from_stdin(self, tmp_path: Path) -> None:
        body = "x = 1\n" * 50
        files = _make_files(
            tmp_path, "pkg/auth", {f"f{i}.py": body for i in range(4)}
        )
        boundaries = [_boundary("auth", "pkg/auth", files)]
        stdin_text = json.dumps(boundaries)
        result = _run_cli(
            "filter",
            "--boundaries",
            "-",
            "--source-root",
            str(tmp_path),
            stdin_text=stdin_text,
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload["stats"]["kept"] == 1
        assert payload["kept"][0]["files_count"] == 4

    def test_filter_empty_input_succeeds(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text("[]", encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload == {
            "kept": [],
            "dropped": [],
            "stats": {"kept": 0, "dropped": 0, "by_reason": {}},
        }

    def test_filter_custom_thresholds(self, tmp_path: Path) -> None:
        # 1-file, 1-line boundary normally drops as too-few-files; relax
        # thresholds via flags
        files = _make_files(tmp_path, "pkg/solo", {"f.py": "x = 1\n"})
        boundaries = [_boundary("solo", "pkg/solo", files)]
        b_path = tmp_path / "boundaries.json"
        b_path.write_text(json.dumps(boundaries), encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
            "--min-files",
            "1",
            "--min-loc",
            "0",
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload["stats"]["kept"] == 1

    def test_filter_generated_code_via_stdin(self, tmp_path: Path) -> None:
        boundaries = [
            _boundary(
                "vendored",
                "pkg/v",
                [
                    "pkg/v/node_modules/react/index.js",
                    "pkg/v/src/App.js",
                ],
            ),
        ]
        result = _run_cli(
            "filter",
            "--boundaries",
            "-",
            "--source-root",
            str(tmp_path),
            stdin_text=json.dumps(boundaries),
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload["stats"]["by_reason"] == {"generated-code": 1}
        assert payload["dropped"][0]["context"]["matched_segment"] == "node_modules/"

    def test_filter_auto_generated_via_stdin(self, tmp_path: Path) -> None:
        body_gen = "// @generated by codegen\n" + ("x = 1;\n" * 50)
        body_plain = "x = 1;\n" * 50
        files = _make_files(
            tmp_path,
            "pkg/codegen",
            {
                "schema.ts": body_gen,
                "model.ts": body_plain,
                "service.ts": body_plain,
            },
        )
        boundaries = [_boundary("codegen", "pkg/codegen", files)]
        result = _run_cli(
            "filter",
            "--boundaries",
            "-",
            "--source-root",
            str(tmp_path),
            stdin_text=json.dumps(boundaries),
        )
        assert result.returncode == 0, result.stderr
        payload = json.loads(result.stdout)
        assert payload["stats"]["by_reason"] == {"auto-generated-tag": 1}

    def test_filter_missing_file_exits_1(self, tmp_path: Path) -> None:
        result = _run_cli(
            "filter",
            "--boundaries",
            str(tmp_path / "missing.json"),
            "--source-root",
            str(tmp_path),
        )
        assert result.returncode == 1
        assert "not found" in result.stderr

    def test_filter_malformed_json_exits_1(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text("{not json", encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
        )
        assert result.returncode == 1
        assert "malformed JSON" in result.stderr

    def test_filter_missing_required_field_exits_1(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text(
            json.dumps([{"name": "a", "files": []}]), encoding="utf-8"
        )
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
        )
        assert result.returncode == 1
        assert "path" in result.stderr

    def test_filter_negative_min_files_exits_1(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text("[]", encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
            "--min-files",
            "-1",
        )
        assert result.returncode == 1
        assert "min-files" in result.stderr

    def test_filter_negative_min_loc_exits_1(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text("[]", encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path),
            "--min-loc",
            "-5",
        )
        assert result.returncode == 1
        assert "min-loc" in result.stderr

    def test_filter_bad_source_root_exits_1(self, tmp_path: Path) -> None:
        b_path = tmp_path / "boundaries.json"
        b_path.write_text("[]", encoding="utf-8")
        result = _run_cli(
            "filter",
            "--boundaries",
            str(b_path),
            "--source-root",
            str(tmp_path / "does-not-exist"),
        )
        assert result.returncode == 1
        assert "source-root" in result.stderr
