/**
 * SKF Manifest - Tracks installed files for uninstall and smart updates.
 * Writes _bmad/_config/manifest.yaml after each install.
 */

const path = require('node:path');
const fs = require('fs-extra');
const yaml = require('js-yaml');

const MANIFEST_DIR = '_bmad/_config';
const MANIFEST_FILE = 'skf-manifest.yaml';

/**
 * Recursively collect all file paths under a directory,
 * returned as paths relative to projectDir.
 */
async function collectFiles(dir, projectDir) {
  const files = [];
  if (!(await fs.pathExists(dir))) return files;

  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const subFiles = await collectFiles(fullPath, projectDir);
      files.push(...subFiles);
    } else {
      files.push(path.relative(projectDir, fullPath));
    }
  }
  return files;
}

/**
 * Build and write the manifest after installation.
 *
 * @param {string} projectDir - Project root
 * @param {object} config - Install config (skfFolder, ides, etc.)
 * @param {object} options - Additional info (version, ideDirectories)
 */
async function writeManifest(projectDir, config, options = {}) {
  const skfFolder = config.skfFolder || '_bmad/skf';
  const skfDir = path.join(projectDir, skfFolder);
  const sidecarDir = path.join(projectDir, '_bmad', '_memory', 'forger-sidecar');

  // Collect all installed files
  const skfFiles = await collectFiles(skfDir, projectDir);
  const sidecarFiles = await collectFiles(sidecarDir, projectDir);

  // Collect IDE skill directory files (installed to each IDE's skills/ dir)
  const ideDirectories = options.ideDirectories || [];
  const ideSkillFiles = [];
  for (const ideDir of ideDirectories) {
    const fullDir = path.join(projectDir, ideDir);
    const files = await collectFiles(fullDir, projectDir);
    ideSkillFiles.push(...files);
  }

  // Collect learning material files
  const learnDir = path.join(projectDir, '_skf-learn');
  const learnFiles = await collectFiles(learnDir, projectDir);

  // Collect output folder gitkeep files
  const outputFiles = [];
  for (const folder of [config.skills_output_folder || 'skills', config.forge_data_folder || 'forge-data']) {
    const gitkeep = path.join(folder, '.gitkeep');
    if (await fs.pathExists(path.join(projectDir, gitkeep))) {
      outputFiles.push(gitkeep);
    }
  }

  const manifest = {
    version: options.version || 'unknown',
    installed_at: new Date().toISOString(),
    action: config._action || 'fresh',
    module: 'skf',
    skf_folder: skfFolder,
    ides: config.ides || [],
    skills_output_folder: config.skills_output_folder || 'skills',
    forge_data_folder: config.forge_data_folder || 'forge-data',
    directories: [skfFolder, '_bmad/_memory/forger-sidecar', ...ideDirectories, ...(learnFiles.length > 0 ? ['_skf-learn'] : [])],
    files: {
      skf: skfFiles,
      sidecar: sidecarFiles,
      ide_skills: ideSkillFiles,
      learning: learnFiles,
      output: outputFiles,
    },
  };

  const manifestDir = path.join(projectDir, MANIFEST_DIR);
  await fs.ensureDir(manifestDir);

  const yamlStr = yaml.dump(manifest, { lineWidth: -1, sortKeys: false });
  await fs.writeFile(
    path.join(manifestDir, MANIFEST_FILE),
    `# SKF Installation Manifest - Generated by installer\n# Do not edit manually\n${yamlStr}`,
    'utf8',
  );
}

/**
 * Read an existing manifest, or return null if none exists.
 */
async function readManifest(projectDir) {
  const manifestPath = path.join(projectDir, MANIFEST_DIR, MANIFEST_FILE);
  try {
    const content = await fs.readFile(manifestPath, 'utf8');
    return yaml.load(content) || null;
  } catch {
    return null;
  }
}

module.exports = { writeManifest, readManifest, MANIFEST_DIR, MANIFEST_FILE };
